templates:
    global:
        torrent_alive: yes
    ### MOVIES
    download-movie:
        discover:
            what:
                - movie_list: trakt movies
            from:
                - piratebay:
                    category: 207
        imdb_lookup: yes
        list_match:
            from:
                - movie_list: trakt movies
        exec:
            allow_background: no
            auto_escape: no
            on_output:
                for_accepted: ruby /usr/share/doc/aria2/xmlrpc/aria2rpc addUri "{{url}}" --dir="home/ali/Downloads/aria2/flexget/Movies/{{ movie_name|replace(':','-') }}" --pause="true"
        # Remove accepted torrents from watchlist in trakt.
        list_remove:
            - trakt_list:
                username: tuxitop
                account: tuxitop
                list: watchlist
        # Mark accepted torrents as collected in trakt.
        list_add:
            - trakt_list:
                username: tuxitop
                account: tuxitop
                list: collection
    ### SERIES
    trakt-shows-480:
        configure_series:
            settings:
                quality: webdl|hdtv <720p !xvid !divx
                exact: yes
            from:
                trakt_list:
                    username: tuxitop
                    account: tuxitop
                    list: watchlist
                    type: shows
    trakt-shows-any:
        configure_series:
            settings:
                quality: webdl|hdtv
                exact: yes
            from:
                trakt_list:
                    username: tuxitop
                    account: tuxitop
                    list: watchlist
                    type: shows
    trakt-discover-show:
        series:
            - Shameless:
                alternate_name: Shameless (US)
        discover:
            what:
                - next_trakt_episodes:
                    username: tuxitop
                    account: tuxitop
                    context: collected
                    list: watchlist
                    strip_dates: yes
            from:
                - piratebay:
                    category: tv
        exec:
            allow_background: no
            auto_escape: no
            on_output:
                for_accepted: ruby /usr/share/doc/aria2/xmlrpc/aria2rpc addUri "{{url}}" --dir="/home/ali/Downloads/aria2/flexget/Series/" --pause="true"
        # Mark accepted torrents as collected in trakt.
        list_add:
            - trakt_list:
                username: tuxitop
                account: tuxitop
                list: collection

tasks:
#    ### MOVIES
#    download-queue:
#        priority: 10
#        trakt_list:
#            username: tuxitop
#            account: tuxitop
#            list: watchlist
#            type: movies
#        accept_all: yes
#        list_add:
#            - movie_list: trakt movies
#
#    movies-NO-YIFY-720p:
#        priority: 20
#        content_size:
#            max: 2000
#        assume_quality: 720p webrip h264 mp3
#        quality: 720p webrip+ h264+ mp3+
#        regexp:
#            reject:
#                - YIFI
#        template: download-movie
#    movies-720p:
#        priority: 30
#        content_size:
#            max: 2000
#        assume_quality: 720p webrip h264 mp3
#        quality: 720p webrip+ h264+ mp3+
#        template: download-movie
#    movies-NO-YIFY-720pOrUp:
#        priority: 40
#        content_size:
#            max: 2000
#        assume_quality: 720p webrip h264 mp3
#        quality: 720p+ webrip+ h264+ mp3+
#        regexp:
#            reject:
#                - YIFI
#        template: download-movie
#    movies-NO-YIFY-720pOrUp:
#        priority: 45
#        content_size:
#            max: 2000
#        assume_quality: 720p webrip h264 mp3
#        quality: 720p+ webrip+ h264+ mp3+
#        template: download-movie

    ### SERIES
    sync-trakt:
        priority: 40
        next_trakt_episodes:
            username: tuxitop
            account: tuxitop
            context: collected
            list: watchlist
        accept_all: yes
        set_series_begin: yes
    series-showRSS:
        priority: 50
        rss: https://showrss.info/user/81827.rss?magnets=true&namespaces=true&name=clean&quality=null&re=null
        template: trakt-shows-any
        series:
            - Shameless:
                alternate_name: Shameless (US)
        accept_all: yes
        exec:
            allow_background: no
            auto_escape: no
            on_output:
                for_accepted: ruby /usr/share/doc/aria2/xmlrpc/aria2rpc addUri "{{url}}" --dir="/home/ali/Downloads/aria2/flexget/Series/" --pause="true"
#        aria2:
#            exclude_samples: yes
#            exclude_non_content: yes
#            do: add-new
#            uri: '{{url}}'
#            aria_config:
#                dir: "home/ali/Downloads/aria2/flexget/Series/{{series_name}}"
#                pause: "true"
        # Mark accepted torrents as collected in trakt.
        list_add:
            - trakt_list:
                username: tuxitop
                account: tuxitop
                list: collection
    series-piratebay:
        priority: 60
        template: trakt-shows-480
        template: trakt-discover-show
    series-any:
        priority: 70
        template: trakt-shows-any
        template: trakt-discover-show
